# Project
title: jekyll-base
description: Jekyll을 시작하기 위한 템플릿입니다.

# Author
author: 심철환
email: a@akaiv.com
github_username: s10n

# Configuration
baseurl: /jekyll-base
permalink: /:title
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - assets

sass:
  style: :compressed

lang: ko
timezone: Asia/Seoul
