# Project
title: Sim Cheolhwan
description: Front-end engineer

# Author
author: 심철환
email: a@akaiv.com
github_username: s10n

# Configuration
permalink: /:title
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - package.json
  - Gruntfile.js
  - node_modules

sass:
  style: :compressed

lang: ko
timezone: Asia/Seoul
